---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: 提供VMware ONTAP vSphere的部署和初始化功能。 
---
= VMware vSphere快速入門工具ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
適用於 VMware vSphere 的 ONTAP 工具是單一 vCenter Server 外掛程式、內含 ONTAP 工具、 VASA Provider 和儲存複寫介面卡（ SRA ）擴充功能。建議所有 ONTAP vSphere 環境使用 ONTAP 工具、因為它會使用最佳實務做法來設定 ESXi 主機設定和配置 ONTAP 儲存設備。虛擬磁碟區（vVols）支援需要VASA Provider、SRA則需搭配VMware Site Recovery Manager一起運作。



== 準備安裝

您將外掛程式部署為虛擬應用裝置、可減少在vCenter Server上個別安裝及註冊每個產品的工作。



=== 部署需求

ONTAP 工具可搭配 VMware vCenter Server 虛擬應用裝置（ vCSA ）使用。您必須在ONTAP 支援的vSphere（包括ESXi系統）上部署這些功能完善的工具。

最小空間和主機規模調整需求為：

[cols="25,75"]
|===
| *系統* | *最低要求* 


| 空間 | 2.1 GB適用於精簡配置安裝、54.0 GB適用於完整配置的安裝 


| 主機規模調整 | 建議記憶體：12 GB、建議CPU：2. 
|===
您應該注意下列授權：

[cols="25,75"]
|===
| *授權* | *說明* 


| SnapMirror | （選用）如果使用vVols複寫、則需要執行SRA和VASA Provider的容錯移轉作業。 


| FlexClone | （選用）執行SRA的測試容錯移轉作業、以及VASA Provider的vVols作業所需的測試容錯移轉作業。 
|===
使用下列預設雙向TCP連接埠的VMware Tools：ONTAP

|===


| *額外需求* | *說明欄* 


 a| 
9083.
 a| 
啟用時、VASA Provider和Storage Replication Adapter（SRA）都會使用此連接埠與vCenter Server通訊。取得TCP/IP設定也需要此連接埠。此連接埠可用於下載 VP 支援套件、存取 Web-CLI 使用者介面、以及控制 VMware 與 VP 之間的路徑通訊。



 a| 
443..
 a| 
根據您設定認證的方式、VMware vCenter Server和儲存系統會偵聽此連接埠上的安全通訊。連接埠用於用戶端 - 伺服器通訊架構。安全連線預設會啟用 443 連接埠。用戶端可以是任何使用 REST API 的自動化用戶端、會啟動與伺服器的連線、而端點則會交換資料。



 a| 
8143.
 a| 
ONTAP 工具會偵聽此連接埠上的安全通訊。連接埠用於用戶端 - 伺服器通訊架構。用戶端可以是任何使用 REST API 的自動化用戶端、會啟動與伺服器的連線、而端點則會交換資料。此連接埠可用於 ONTAP 工具服務和匯出 ONTAP 工具伺服器記錄檔。register.html 頁面託管在此連接埠上。其餘的交換器會暴露在此連接埠上。



 a| 
8443
 a| 
此連接埠用於遠端外掛程式服務。

|===
最低儲存與應用程式需求：

|===
| *儲存設備、主機及應用程式* | *版本要求* 


| ONTAP | ONTAP 9.7 、 9.8P1 或更新版本。 


| VMware vSphere、vCenter伺服器、ESXi主機、Site Recovery Manager（SRM）、外掛應用程式及資料庫欄1 | 請參閱 https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["互通性對照表工具"^] 
|===


=== VMware工具需求ONTAP

* 設定及設定vCenter Server環境。
* 下載.ova檔案。
* vCenter Server執行個體的登入認證。
* 刪除瀏覽器快取、以避免在部署ONTAP VMware工具期間發生任何瀏覽器快取問題。
* 設定虛擬應用裝置用來回應ICMP Ping的預設閘道。
* 虛擬應用裝置的有效DNS主機名稱。




=== SRA的選用需求

如果您要部署與 VMware Site Recovery Manager 搭配使用的虛擬應用裝置、則必須下載： * `.tar.gz` 使用 SRM 應用裝置時的 SRA 檔案。



== 部署ONTAP 各種功能

.步驟
. 下載 `.zip` 包含的二進位檔和簽署憑證的檔案 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支援網站"^] 至vSphere Client系統以部署ONTAP 這些功能。
. 擷取 `.zip` 歸檔並部署 `.ova` 檔案：
+
如果要部署SRA、您必須在來源和目的地站台上部署「.ova」檔案。

. 登入 vSphere Web Client 、選取 * 首頁 * > * 主機與叢集 * 。
. 以滑鼠右鍵按一下所需的資料中心、然後按一下*部署OVF範本*。
+
如果您使用的是 vCenter7.0u3e 及更新版本、請執行下列動作、否則請繼續執行步驟 5 。這是可選的步驟、可確認 OVA 二進位完整性未遭到竄改。

+
** 從 NetApp 支援網站 下載 _OTV_INT_ROOT_CERT_CHAIL.pem_ 檔案。
** 瀏覽至 * vCenter * > * 管理 * > * 憑證管理 * 。
** 按一下 * 新增信任的根憑證 * 選項。
** 按一下 * 瀏覽 * 並提供 _OTV_INT_ROOT_CERT_CHAIL.pem_ 檔案的路徑。
** 按一下「 * 新增 * 」。
+

NOTE: 出現「 Entrust 程式碼簽署 - OVCS2 （信任的憑證）」訊息、確認下載 OVA 檔案的完整性。如果您看到「 Entrust 程式碼簽署 - OVCS2 （無效憑證）」訊息、請將 VMware vCenter Server 升級至 7.0U3E 或更新版本。



. 您可以輸入.ova檔案的URL、或瀏覽至儲存.ova檔案的資料夾、然後按一下*「下一步*」。
. 輸入完成部署所需的詳細資料。



NOTE: （選用）如果您想要在不登錄vCenter Server的情況下建立容器、請選取「Configure vCenter（設定vCenter）」或「Enable VCF（啟用VCF）」區段中的「Enable VMware Cloud Foundation（VCF）（啟用VMware Cloud Foundation（VCF））」核取方

您可以從*工作*索引標籤檢視部署進度、然後等待部署完成。

在部署檢查和驗證過程中、會執行驗證。如果部署失敗、請執行下列步驟：

. 驗證 vpserver/logs/checksum 。 log 。如果它顯示「 Checksum 驗證失敗」、您可以在同一個記錄中看到失敗的 Jar 驗證。
+
記錄檔包含執行 _shap256sum -c /opt/netapp/vpserver/conf/checksum_ 。

. 驗證 vscserver/log/checksum 。 log 。如果它顯示「 Checksum 驗證失敗」、您可以在同一個記錄中看到失敗的 Jar 驗證。
+
記錄檔包含執行 _shap256sum -c /opt/NetApp/vscerver/etc/checksums_ 。





=== 在SRM上部署SRA

您可以在Windows SRM伺服器或8.2 SRM設備上部署SRA。



==== 在SRM設備上上傳及設定SRA

.步驟
. 從下載「.tar.gz」檔案 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp 支援網站"^]。
. 在「SRM應用裝置」畫面上、按一下「*儲存複寫介面卡*」>「*新介面卡*」。
. 將「.tar.gz」檔案上傳至SRM。
. 重新掃描介面卡、確認「SRM儲存複寫介面卡」頁面中的詳細資料已更新。
. 使用管理員帳戶登入SRM設備、並使用該工具登入。
. 切換至root使用者：「u root」
. 在記錄位置輸入命令以取得SRA泊塢視窗所使用的Docker ID：「Docker ps -l」
. 登入容器ID：「Docker執行-it -u SRM <container id> sh」
. 使用 ONTAP 工具設定 SRM IP 位址和密碼： `perl command.pl -I <otv-IP> administrator <otv-password>`此時會顯示一則成功訊息、確認儲存認證資料已儲存。




==== 正在更新SRA認證

.步驟
. 使用下列方法刪除/SRM/SRA/confDirectory的內容：
+
.. "CD /SRM/SRA/conf"
.. 「rm -RF *」


. 執行perl命令以新認證設定SRA：
+
.. 「CD /SRM/SRA/」
.. `perl command.pl -I <otv-IP> administrator <otv-password>`






==== 啟用VASA Provider和SRA

.步驟
. 使用 OVA ONTAP 工具部署期間提供的 vCenter IP 登入 vSphere Web 用戶端。
. 在捷徑頁面中、按一下外掛程式區段下方的 * NetApp ONTAP tools* 。
. 在 ONTAP 工具的左窗格中、 * 設定 > 系統管理設定 > 管理功能 * 、並啟用所需的功能。
+

NOTE: 預設會啟用Vasa Provider。如果您想要使用vVols資料存放區的複寫功能、請使用「啟用vVols複寫切換」按鈕。

. 輸入ONTAP 資訊工具的IP位址和管理員密碼、然後按一下「*套用*」。

