---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: 根據預設、 ONTAP 工具會使用指定的連接埠來啟用其元件（包括儲存系統和 VMware vCenter Server ）之間的通訊。如果您已啟用防火牆、則必須確定防火牆已設定為允許例外。 
---
= ONTAP 工具的連接埠需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據預設、 ONTAP 工具會使用指定的連接埠來啟用其元件（包括儲存系統和 VMware vCenter Server ）之間的通訊。如果您已啟用防火牆、則必須確定防火牆已設定為允許例外。

對於 Windows 以外的防火牆、您應該手動授予 ONTAP 工具使用的特定連接埠存取權。如果您未授予存取這些連接埠的權限、則會顯示下列錯誤訊息。

「無法與伺服器通訊。

使用下列預設雙向TCP連接埠的VMware Tools：ONTAP

|===


| *預設連接埠號碼* | *說明* 


 a| 
9083.
 a| 
啟用時、VASA Provider和Storage Replication Adapter（SRA）都會使用此連接埠與vCenter Server通訊。取得TCP/IP設定也需要此連接埠。需要在防火牆上啟用此連接埠、從 ESXi 主機到 VMware vSphere 應用程式的 ONTAP 工具。此連接埠可用於下載 VP 支援套件、存取 Web-CLI 使用者介面、以及控制 VMware 與 VP 之間的路徑通訊。



 a| 
443..
 a| 
根據您設定認證的方式、VMware vCenter Server和儲存系統會偵聽此連接埠上的安全通訊。連接埠用於用戶端 - 伺服器通訊架構。安全連線預設會啟用 443 連接埠。用戶端可以是任何使用 REST API 的自動化用戶端、會啟動與伺服器的連線、而端點則會交換資料。



 a| 
8143.
 a| 
ONTAP 工具會偵聽此連接埠上的安全通訊。連接埠用於用戶端 - 伺服器通訊架構。用戶端可以是任何使用 REST API 的自動化用戶端、會啟動與伺服器的連線、而端點則會交換資料。此連接埠可用於 ONTAP 工具服務和匯出 ONTAP 工具伺服器記錄檔。register.html 頁面託管在此連接埠上。其餘的交換器會暴露在此連接埠上。



 a| 
8443
 a| 
此連接埠用於 VMware vSphere 外掛程式服務的 ONTAP 工具。



 a| 
7.
 a| 
ONTAP 工具會將回應要求傳送至 ONTAP 、以驗證連線能力、而且只有在新增儲存設備時才需要
可在稍後停用。

|===

NOTE: 在部署ONTAP VMware Tools之前、您應該先啟用網際網路控制訊息傳輸協定（ICMP）。

如果停用 ICMP 、則 ONTAP 工具的初始組態將會失敗、而 ONTAP 工具在部署後無法啟動 VMware vSphere 和 VASA Provider 服務的 ONTAP 工具。部署後、您必須手動啟用 VMware vSphere 和 VASA Provider 服務的 ONTAP 工具。
