---
permalink: deploy/task_deploy_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: 若要使用適用於 VMware vSphere 應用程式的 ONTAP 工具、請在您的環境中部署適用於 VMware vSphere 的 ONTAP 工具、並指定所需的參數。 
---
= 如何部署ONTAP 資訊工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要使用適用於 VMware vSphere 應用程式的 ONTAP 工具、請在您的環境中部署適用於 VMware vSphere 的 ONTAP 工具、並指定所需的參數。

*您需要的是什麼*

* 您必須擁有支援的 vCenter Server 版本。
+

NOTE: 您可以在 Windows 部署 vCenter Server 或 VMware vCenter Server 虛擬應用裝置（ vCSA ）部署中、註冊適用於 VMware vSphere 的 ONTAP 工具。

+
https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["互通性對照表工具"^]

* 您必須已設定及設定vCenter Server環境。
* 您必須為虛擬機器設定ESXi主機。
* 您必須已下載_.ova_檔案。
* 您必須擁有vCenter Server執行個體的系統管理員登入認證。
* 您應該已登出並關閉vSphere Client的所有瀏覽器工作階段、並刪除瀏覽器快取、以避免在ONTAP 部署完各種VMware應用程式時發生任何瀏覽器快取問題。
* 您必須已啟用網際網路控制訊息傳輸協定（ ICMP ）。
+
如果停用 ICMP 、則用於 VMware vSphere 的 ONTAP 工具初始組態將會失敗。部署後、您必須手動啟用 VMware vSphere 和 VASA Provider 服務的 ONTAP 工具。



*關於此工作*

根據預設、 VASA Provider 會啟用、以便全新安裝適用於 VMware vSphere 的 ONTAP 工具。但如果是從舊版升級、則會保留 VASA Provider 的狀態、您可能需要手動啟用 VASA Provider 。

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["啟用VASA Provider以設定虛擬資料存放區"]

*步驟*

. 登入vSphere Client。
. 選取 * 首頁 * > * 主機與叢集 * 。
. 以滑鼠右鍵按一下所需的資料中心、然後按一下 * 部署 OVF 範本 ... * 。
+

NOTE: 請勿將 ONTAP 工具 VMware vSphere 虛擬機器部署在其管理的 VVols 資料存放區上。

. 選取適當的方法、提供ONTAP 適用於VMware的部署檔案以供使用、然後按一下*下一步*。
+
|===


| *位置* | *行動* 


 a| 
URL
 a| 
提供適用於ONTAP 各種資訊工具的_.ova_檔案URL。



 a| 
資料夾
 a| 
將包含 .ova 檔案的 .zip 檔案解壓縮至您的本機系統。在「選取 OVF 範本」頁面上、指定 .ova 檔案在擷取資料夾內的位置。

|===
. 輸入詳細資料以自訂部署精靈。
+
（選用）在「Configure vCenter（設定vCenter）」或「Enable VCF（啟用VCF）」區段中、選取「Enable VMware Cloud Foundation（VCF）*（啟用VMware Cloud Foundation（VCF）*）」核取方塊、並提供ONTAP 密碼以供使用。ONTAP 工具會以編碼格式儲存使用者詳細資料。對於從 ONTAP 工具到 vCenter 的任何通訊、都會使用這些 vCenter 使用者詳細資料。
您不需要提供IP位址、但必須提供密碼。
如需完整詳細資料、請參閱下列內容。

+
** link:../deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html["部署自訂考量"]
** link:../deploy/vmware_cloud_foundation_mode_deployment.html["VMware Cloud Foundation ONTAP 部署功能、適用於各種VMware工具"]


. 檢閱組態資料、然後按一下*「下一步*」完成部署。
+
當您等待部署完成時、可以從「工作」索引標籤檢視部署進度。

. 開啟ONTAP VMware Tools虛擬機器的電源、然後開啟執行ONTAP VMware Tools的虛擬機器主控台。
. 驗證ONTAP 部署完成後、是否執行了一些功能不完整的工具。
. 如果 ONTAP 工具未在任何 vCenter Server 上登錄、請使用 `\https://appliance_ip:8143/Register.html` 登錄 ONTAP 工具執行個體。Register.html 會將您重新導向至「瀏覽器」頁面。從 ONTAP 工具 9.12 開始、 ONTAP 工具與 vCenter 的登錄會從瀏覽器頁面開始。
+
使用 POST API 從 9.12 開始向 vCenter 登錄 ONTAP 工具。

+
[listing]
----
/2.0/plugin/vcenter
----
. 登出並重新登入vSphere Client、以檢視部署ONTAP 的功能表工具。
+
在vSphere Client中更新外掛程式可能需要幾分鐘的時間。

+
*疑難排解：*如果您在登入後仍無法檢視外掛程式、則必須清除vSphere Client快取。

+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["清除vSphere快取下載的外掛程式套件"]



link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["啟用VASA Provider以設定虛擬資料存放區"]

*相關資訊*

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Software%2FVirtual_Storage_Console_for_VMware_vSphere%2FError_during_fresh_deployment_of_virtual_appliance_for_VSC%252C_VASA_Provider%252C_and_SRA["針對VSC、VASA Provider及SRA重新部署虛擬應用裝置時發生錯誤"]
