---
permalink: protect/task_enable_storage_replication_adapter.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere的支援功能可讓SRA功能與VSC搭配使用、以設定災難恢復。ONTAP 
---
= 啟用SRA來保護資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere的支援功能可讓SRA功能與VSC搭配使用、以設定災難恢復。ONTAP

*您需要的是什麼*

* 您必須設定vCenter Server執行個體並設定ESXi。
* 您必須已部署ONTAP 完各種功能不實的工具。
* 您必須下載SRA外掛程式的「.msi」檔案、或SRM應用裝置的「.tar.gz」檔案、才能設定Site Recovery Manager（SRM）災難恢復解決方案。
+
https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-B3A49FFF-E3B9-45E3-AD35-093D896596A0.html["Site Recovery Manager安裝與組態Site Recovery Manager 8.2"] 有更多資訊。



*關於此工作*

啟用VASA Provider和SRA功能的靈活度、可讓您只執行企業所需的工作流程。

*步驟*

. 登入VMware vSphere的網路使用者介面。
. 在vSphere Client中、按一下*功能表*>* ONTAP 功能表工具主控台*。
. 按一下 * 設定 * 。
. 按一下*管理設定*索引標籤中的*管理功能*。
. 在「*管理功能*」對話方塊中、選取要啟用的SRA副檔名。
. 輸入ONTAP 「資訊工具」的IP位址和管理員密碼、然後按一下「*套用*」。
. 您可以使用下列其中一種方法來部署SRA：
+
|===


 a| 
*適用於Windows SRM *
| *適用於SRM應用裝置* 


 a| 
.. 按兩下下載的SRA外掛程式「.msi-」安裝程式。
.. 依照螢幕上的指示操作。
.. 輸入已部署ONTAP 的各種功能的IP位址和密碼。

 a| 
.. 存取SRM應用裝置頁面、然後前往SRM應用裝置的「儲存複寫介面卡」頁面。
.. 按一下「*新增介面卡*」。
.. 將SRA外掛程式的_.tar.gz_安裝程式上傳至SRM。
.. 重新掃描介面卡、確認「SRM儲存複寫介面卡」頁面中的詳細資料已更新。


|===
+
您必須登出vSphere Client、然後再次登入、以驗證所選的擴充功能是否可供組態使用。



*相關資訊*

link:../concepts/concept_manage_disaster_recovery_setup_using_srm.html["設定儲存複寫介面卡以進行災難恢復"]
