---
permalink: protect/task_configure_storage_replication_adapter_for_san_environment.html 
sidebar: sidebar 
keywords:  
summary: 您必須先設定儲存系統、再執行Site Recovery Manager（SRM）的儲存複寫介面卡（SRA）。 
---
= 設定SAN環境的儲存複寫介面卡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先設定儲存系統、再執行Site Recovery Manager（SRM）的儲存複寫介面卡（SRA）。

*您需要的是什麼*

您必須在受保護的站台和恢復站台上安裝下列程式：

* SRM
+
有關安裝SRM的說明文件、請參閱VMware網站。

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager文件"]

* SRA
+
介面卡安裝在SRM上。



*步驟*

. 確認主ESXi主機已連線至受保護站台上主要儲存系統的LUN。
. 確認LUN位於igroup中、且主儲存系統的「ostype-」選項設為_VMware_。
. 確認恢復站台的ESXi主機與儲存虛擬機器（SVM）之間具有適當的FC或iSCSI連線。
+
您可以驗證ESXi主機是否已在SVM上連接本機LUN、或是在SVM上使用「FCP show啟動器」命令或「iSCSI show啟動器」命令。





== 設定NAS環境的儲存複寫介面卡

*您需要的是什麼*

您必須在受保護的站台和恢復站台上安裝下列程式：

* SRM
+
如需安裝SRM的相關文件、請參閱VMware網站。

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager文件"]

* SRA
+
介面卡安裝在SRM和SRA伺服器上。



*步驟*

. 確認受保護站台的資料存放區包含已向vCenter Server註冊的虛擬機器。
. 確認受保護站台的ESXi主機已從儲存虛擬機器（SVM）掛載NFS匯出磁碟區。
. 使用Array Manager精靈將陣列新增至SRM時、請確認「* NFS Addresses *（* NFS位址*）」欄位中已指定有效位址、例如有NFS匯出的IP位址、主機名稱或FQDN。
. 在恢復站台的每個ESXi主機上使用「ping」命令、驗證主機是否有可存取用於從SVM匯出NFS的IP位址的VMkernel連接埠。


https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]
