---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 為了簡化使用 vCenter Server 權限和角色型存取控制（ RBAC ）的過程、 ONTAP 工具提供標準的 ONTAP 工具角色、可讓您執行重要的 ONTAP 工具工作。還有一個唯讀角色、可讓您檢視資訊、但不執行任何工作。 
---
= 標準角色隨ONTAP 附於整套的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了簡化使用 vCenter Server 權限和角色型存取控制（ RBAC ）的過程、 ONTAP 工具提供標準的 ONTAP 工具角色、可讓您執行重要的 ONTAP 工具工作。還有一個唯讀角色、可讓您檢視資訊、但不執行任何工作。

標準 ONTAP 工具角色具有必要的 ONTAP 工具專屬權限、以及使用者執行 ONTAP 工具工作所需的原生 vCenter Server 權限。此外、這些角色也會設定成擁有所有受支援版本vCenter Server所需的權限。

身為管理員、您可以視需要指派這些角色給使用者。


NOTE: 當您將 ONTAP 工具升級至最新版本時、標準角色會自動升級以搭配新版本的工具使用。

按一下 vSphere Client 首頁上的 * 角色 * 、即可檢視 ONTAP 工具標準角色。

ONTAP 工具提供的角色可讓您執行下列工作：

|===


| *角色* | *說明* 


 a| 
VSC管理員
 a| 
提供執行所有 ONTAP 工具工作所需的所有原生 vCenter Server 權限和 ONTAP 工具專屬權限。



 a| 
VSC唯讀
 a| 
提供 ONTAP 工具的唯讀存取權。這些使用者無法執行任何存取控制的 ONTAP 工具動作。



 a| 
VSC配置
 a| 
提供資源配置儲存所需的所有原生 vCenter Server 權限和 ONTAP 工具專屬權限。您可以執行下列工作：

* 建立新的資料存放區
* 銷毀資料存放區
* 檢視儲存功能設定檔的相關資訊


|===


== 使用 ONTAP 工具標準角色的準則

當您使用VMware ONTAP vSphere角色的標準版基礎架構工具時、您應該遵循某些準則。

您不應直接修改標準角色。如果您這麼做、 ONTAP 工具會在您每次升級時覆寫您的變更。每次升級 ONTAP 工具時、安裝程式都會更新標準角色定義。如此可確保您的 ONTAP 工具版本以及 vCenter Server 所有支援版本的角色都是最新的。

不過、您可以使用標準角色來建立專為您環境量身打造的角色。若要這麼做、您應該複製 ONTAP 工具標準角色、然後編輯複製的角色。透過建立新角色、即使您重新啟動或升級 ONTAP 工具 Windows 服務、也可以維持此角色。

您可以使用 ONTAP 工具標準角色的一些方法包括：

* 使用標準 ONTAP 工具角色來執行所有 ONTAP 工具工作。
+
在此案例中、標準角色提供使用者執行 ONTAP 工具工作所需的所有權限。

* 合併角色以擴充使用者可以執行的工作。
+
如果標準 ONTAP 工具角色為您的環境提供太多精細度、您可以建立包含多個角色的較高層級群組來擴充角色。

+
如果使用者需要執行其他需要額外原生 vCenter Server 權限的非 ONTAP 工具工作、您可以建立提供這些權限的角色、並將其新增至群組。

* 建立更精細的角色。
+
如果貴公司要求您實作的角色比標準 ONTAP 工具角色更具限制性、您可以使用 ONTAP 工具角色來建立新角色。

+
在這種情況下、您將會複製必要的 ONTAP 工具角色、然後編輯複製的角色、使其僅擁有使用者所需的權限。


