---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 為了簡化vCenter Server權限與角色型存取控制（RBAC）的使用、Virtual Storage Console（VSC）提供標準VSC角色、讓您能夠執行關鍵VSC工作。此外、也有唯讀角色可讓您檢視VSC資訊、但無法執行任何工作。 
---
= 標準角色隨ONTAP 附於整套的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了簡化vCenter Server權限與角色型存取控制（RBAC）的使用、Virtual Storage Console（VSC）提供標準VSC角色、讓您能夠執行關鍵VSC工作。此外、也有唯讀角色可讓您檢視VSC資訊、但無法執行任何工作。

標準VSC角色具有必要的VSC專屬權限、以及使用者執行VSC工作所需的原生vCenter Server權限。此外、這些角色也會設定成擁有所有受支援版本vCenter Server所需的權限。

身為管理員、您可以視需要指派這些角色給使用者。


NOTE: 當您將VSC升級至最新版本時、系統會自動升級標準角色、以搭配新版VSC使用。

您可以按一下vSphere Client首頁上的*角色*來檢視VSC標準角色。

VSC提供的角色可讓您執行下列工作：

|===


| *角色* | *說明* 


 a| 
VSC管理員
 a| 
提供執行所有VSC工作所需的所有原生vCenter Server權限和VSC專屬權限。



 a| 
VSC唯讀
 a| 
提供VSC的唯讀存取權。這些使用者無法執行任何存取控制的VSC動作。



 a| 
VSC配置
 a| 
提供配置儲存設備所需的所有原生vCenter Server權限和VSC專屬權限。您可以執行下列工作：

* 建立新的資料存放區
* 銷毀資料存放區
* 檢視儲存功能設定檔的相關資訊


|===


== 使用VSC標準角色的準則

當您使用VMware ONTAP vSphere角色的標準版基礎架構工具時、您應該遵循某些準則。

您不應直接修改標準角色。如果您這麼做、VSC會在您每次升級VSC時覆寫您的變更。每次升級VSC時、安裝程式都會更新標準角色定義。這樣做可確保您的VSC版本以及所有受支援版本的vCenter Server的角色都是最新的。

不過、您可以使用標準角色來建立專為您環境量身打造的角色。若要這麼做、您應該複製VSC標準角色、然後編輯複製的角色。藉由建立新角色、即使您重新啟動或升級VSC Windows服務、也能維持此角色。

您可以使用VSC標準角色的部分方法包括：

* 使用標準VSC角色執行所有VSC工作。
+
在此案例中、標準角色提供使用者執行VSC工作所需的所有權限。

* 合併角色以擴充使用者可以執行的工作。
+
如果標準VSC角色為您的環境提供過多精細度、您可以建立包含多個角色的較高層級群組來擴充角色。

+
如果使用者需要執行其他需要額外原生vCenter Server權限的非VSC工作、您可以建立提供這些權限的角色、並將其新增至群組。

* 建立更精細的角色。
+
如果貴公司要求您實作比標準VSC角色更具限制性的角色、您可以使用VSC角色來建立新角色。

+
在這種情況下、您會複製必要的VSC角色、然後編輯複製的角色、使其僅擁有使用者所需的權限。


