---
permalink: concepts/concept_how_to_configure_data_ontap_role_based_access_control_for_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 如果您想要使用適用於 VMware vSphere 的 ONTAP 工具來進行角色型存取控制、則必須在儲存系統上設定 ONTAP 角色型存取控制（ RBAC ）。您可以使用ONTAP 「介紹RBAC」功能、建立一個或多個存取權限有限的自訂使用者帳戶。 
---
= 如何針對ONTAP VMware vSphere的VMware vSphere、設定ONTAP 以角色為基礎的驗證工具存取控制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要在VMware vSphere上使用角色型存取控制搭配使用VMware vSphere的VMware工具、則必須在ONTAP 儲存系統上設定以角色為基礎的存取控制（RBAC）ONTAP 。您可以使用ONTAP 「介紹RBAC」功能、建立一個或多個存取權限有限的自訂使用者帳戶。

ONTAP 工具和 SRA 可以存取叢集層級或儲存虛擬機器（ SVM ） SVM 層級的儲存系統。如果您是在叢集層級新增儲存系統、則必須提供管理使用者的認證、以提供所有必要的功能。如果您是直接新增SVM詳細資料來新增儲存系統、您必須注意、「vsadmin」使用者並不具備執行特定工作所需的全部角色和功能。

VASA Provider只能在叢集層級存取儲存系統。如果特定儲存控制器需要 VASA Provider 、則即使您使用的是 ONTAP 工具或 ONTAP 、也必須將儲存系統新增至叢集層級的工具。

若要建立新的使用者、並將叢集或SVM連線ONTAP 至VMware Tools、您應該執行下列步驟：

* 使用 ONTAP System Manager 9.8P1 或更新版本建立叢集管理員或 SVM 管理員角色。請參閱 link:../configure/task_configure_user_role_and_privileges.html["設定使用者角色和權限"] 以取得更多資訊。
* 使用ONTAP NetApp建立已指派角色的使用者、並使用NetApp建立適當的應用程式集
+
您需要這些儲存系統認證、才能設定 ONTAP 工具的儲存系統。您可以在 ONTAP 工具中輸入認證、為 ONTAP 工具設定儲存系統。每次使用這些認證登入儲存系統時、您都會擁有在 ONTAP 中設定的 ONTAP 工具功能權限、同時也會建立認證。

* 將儲存系統新增至 ONTAP 工具、並提供您剛建立的使用者認證




== ONTAP 工具角色

ONTAP 工具會將 ONTAP 權限分類為下列 ONTAP 工具角色集：

* 探索
+
可探索所有連線的儲存控制器

* 建立儲存設備
+
可建立磁碟區和邏輯單元編號（LUN）

* 修改儲存設備
+
實現儲存系統的大小調整和重複資料刪除

* 摧毀儲存設備
+
可銷毀磁碟區和LUN





== VASA供應商角色

您只能在叢集層級建立原則型管理。此角色可利用儲存功能設定檔、針對儲存設備進行原則型管理。



== SRA角色

SRA將ONTAP 「不支援功能」權限分類為叢集層級或SVM層級的SAN或NAS角色。這可讓使用者執行SRM作業。

當您將叢集新增至 ONTAP 工具時、 ONTAP 工具會執行 ONTAP RBAC 角色的初始權限驗證。如果您已新增直接 SVM 儲存 IP 、則 ONTAP 工具不會執行初始驗證。ONTAP 工具稍後會檢查並強制執行工作流程中的權限。
