---
permalink: concepts/concept_manage_disaster_recovery_setup_using_srm.html 
sidebar: sidebar 
keywords:  
summary: 您可以在vCenter Server中建立及管理災難恢復設定、以及VMware的Site Recovery Manager（SRM）。 
---
= 設定災難恢復設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在vCenter Server中建立及管理災難恢復設定、以及VMware的Site Recovery Manager（SRM）。

VASA Provider現在內建儲存複寫介面卡（SRA）功能。如果您已在資料中心中設定vVols資料存放區、然後針對vVols資料存放區進行還原、則不需要另外安裝SRA來進行災難恢復。在Site Recovery Manager（SRM）中、您必須配對受保護和恢復站台。站台配對完成後、SRM組態的下一部分即是設定陣列配對、讓SRM與儲存系統通訊、以探索裝置和裝置複寫。您必須先在SRM中建立站台配對、才能設定陣列配對。

此版本ONTAP 的支援功能可讓您選擇使用同步SnapMirror組態進行災難恢復。


NOTE: VMware Site Recovery Manager（SRM）不使用SRA來管理vVols資料存放區的災難恢復。VASA Provider則用於ONTAP 複寫及容錯移轉、以控制VVols資料存放區在更新版本的叢集上。

請參閱 link:../protect/task_enable_storage_replication_adapter.html["啟用儲存複寫介面卡"] 程序一節。

.quick 重新同步功能啟動
您可以啟用 quick 重新同步旗標、以在 SRA 中執行重新保護和還原作業。這僅適用於以非同步 SnapMirror 關係為磁碟區備份的資料存放區。由於重新同步不會在傳輸新資料之前產生儲存效率負荷、因此可以加快目的地 Volume 的重新同步時間。根據預設、 quick （快速）重新同步不會啟用。建議啟用 quick 重新同步旗標：

* 當重新同步的來源未啟用 Volume Effeness.
* 減少重新同步時間比保留網路上所有可能的儲存效率更重要。


請依照下列步驟啟用 quick （快速）重新同步旗標：

.步驟
. 登入控制面板、網址為 _https ： <IP address> ： 9083_ 、然後按一下網路型 CLI 介面。
. 執行命令 `vp updateconfig -key=snapmirror.quick.resync.enabled -value=true`。
. 執行命令 `vp reloadconfig`。

