---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere的支援VMware vSphere的支援環境、這些環境使用的是VMware vSphere的支援功能。ONTAP MetroCluster ONTAP大部分支援都是自動的。不過、當您將 MetroCluster 環境與 ONTAP 工具和 VASA Provider 搭配使用時、可能會發現一些差異。 
---
= 支援的支援支援VMware的組態MetroCluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere的支援VMware vSphere的支援環境、這些環境使用的是VMware vSphere的支援功能。ONTAP MetroCluster ONTAP大部分支援都是自動的。不過、當您將 MetroCluster 環境與 ONTAP 工具和 VASA Provider 搭配使用時、可能會發現一些差異。



== MetroCluster 組態和 ONTAP 工具

您必須確保 ONTAP 工具在主要站台和次要站台上探索儲存系統控制器。通常、 ONTAP 工具會自動探索儲存控制器。如果您使用的是叢集管理 LIF 、則最好確認 ONTAP 工具已在兩個站台上探索到叢集。否則、您可以手動將儲存控制器新增至 ONTAP 工具。您也可以修改 ONTAP 工具用來連線至儲存控制器的使用者名稱和密碼配對。

發生切換時、次要站台上的SVM會接管。這些SVM的名稱後面會加上「-MC」字尾。如果在執行資源存放區資源配置等作業時發生切換作業、則資料存放區所在的SVM名稱會變更為包含「`-MC」字尾。當發生切換時、此後置會捨棄、而且主要站台上的SVM會恢復控制權。


NOTE: 如果您已將具有 MetroCluster 組態的直接 SVM 新增至 ONTAP 工具、則在切換後、 SVM 名稱的變更（加上「 -MC 」尾碼）不會反映出來。所有其他切換作業仍會正常執行。

當切換或切換時、 ONTAP 工具可能需要幾分鐘的時間來自動偵測並探索叢集。如果在執行 ONTAP 工具作業（例如資源配置資料存放區）時發生這種情況、您可能會遇到延遲。



== 提供者MetroCluster

VASA Provider會自動支援使用MetroCluster 不完整組態的環境。在VASA Provider環境中、切換是透明的。您無法將直接SVM新增至VASA Provider。


NOTE: VASA Provider在切換後、不會在次要站台上的SVM名稱加上「-MC」字尾。



== 內部組態與SRA MetroCluster

儲存複寫介面卡（ SRA ）支援使用 MetroCluster 組態（ MCC ）搭配 NFS 、 iSCSI 和 FCP 傳輸協定的環境。

所有儲存虛擬機器（ SVM ）名稱在 MCC 叢集上都應是唯一的、這是 MCC SRA 組態的先決條件。如果名稱不是唯一的、則會造成衝突、且 SRA 工作流程會失敗。

必要行動：

. 在執行 MCC 切換或切換後、請確定來源叢集上的 _SnapMirror list-destinations_ 命令會顯示正確的輸出、並顯示新的 SVM 名稱（ <vserver_name> - MC ）。命令可能需要 30 分鐘才能執行。
. 在繼續進行其他的 SRA 工作流程之前、請先從 SRM UI 執行「探索裝置」作業。此作業可確保 SRM 在切換或切換後、能夠察覺 SVM 名稱的變更。

