---
permalink: configure/concept_requirements_for_registering_vsc_in_multiple_vcenter_servers_environment.html 
sidebar: sidebar 
keywords:  
summary: 如果您在單一 VMware vSphere HTML5 用戶端正在管理多個 vCenter Server 執行個體的環境中使用適用於 VMware vSphere 的 ONTAP ® 工具、 您必須在每個 vCenter Server 上註冊一個 ONTAP 工具執行個體、以便在 ONTAP 工具和 vCenter Server 之間進行一對一配對。如此一來、您就能從單一vSphere HTML5用戶端、以連結模式和非連結模式、同時管理執行vCenter 6.0或更新版本的所有伺服器。 
---
= 在多個 vCenter Server 環境中登錄 ONTAP 工具的需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在單一 VMware vSphere HTML5 用戶端正在管理多個 vCenter Server 執行個體的環境中使用適用於 VMware vSphere 的 ONTAP 工具、 您必須在每個 vCenter Server 上註冊一個 ONTAP 工具執行個體、以便在 ONTAP 工具和 vCenter Server 之間進行一對一配對。如此可讓您從單一 vSphere 5 用戶端、以連結模式和非連結模式、管理所有執行 vCenter 7.0 或更新版本的伺服器。


NOTE: 如果您想要將 ONTAP 工具與 vCenter Server 搭配使用、則必須為您要管理的每個 vCenter Server 執行個體設定或登錄一個 ONTAP 工具執行個體。每個已登錄的 ONTAP 工具執行個體必須是相同版本。

連結模式會在vCenter Server部署期間自動安裝。連結模式使用Microsoft Active Directory應用程式模式（ADAM）、在多個vCenter Server系統之間儲存及同步資料。

使用 vSphere HTML5 用戶端跨多個 vCenter Server 執行 ONTAP 工具工作、需要下列條件：

* 您想要管理的 VMware 庫存中的每個 vCenter Server 、都必須有單一 ONTAP 工具伺服器、以獨一無二的一對一配對方式註冊。
+
例如、您可以將 ONTAP 工具伺服器 A 登錄至 vCenter Server A 、將 ONTAP 工具伺服器 B 登錄至 vCenter Server B 、將 ONTAP 工具伺服器 C 登錄至 vCenter Server C 等。

+
您 * 無法 * 將 ONTAP 工具伺服器 A 登錄至 vCenter Server A 和 vCenter Server B

+
如果 VMware 庫存包含的 vCenter Server 沒有註冊 ONTAP 工具伺服器、但有一或多個 vCenter Server 已註冊 ONTAP 工具、 然後、您可以檢視 ONTAP 工具的執行個體、並針對已註冊 ONTAP 工具的 vCenter Server 執行 ONTAP 工具作業。

* 您必須為登錄到單一登入（ SSO ）的每個 vCenter Server 擁有 ONTAP 工具專屬的檢視權限。
+
您也必須擁有正確的RBAC權限。



當您執行的工作需要指定 vCenter Server 時、畫面左上角的 * 執行個體 * 選取器會以英數字元順序顯示可用的 vCenter Server 。預設vCenter Server永遠是下拉式清單中的第一個伺服器。

如果已知儲存設備的位置（例如、當您使用資源配置精靈且資料存放區位於由特定vCenter Server管理的主機上時）、vCenter Server清單會顯示為唯讀選項。只有在您使用滑鼠右鍵選項選取vSphere Web Client中的項目時、才會發生此情況。

ONTAP 工具會在您嘗試選取其不管理的物件時發出警告。

您可以從 ONTAP 工具摘要頁面、根據特定的 vCenter Server 來篩選儲存系統。每個已登錄 vCenter Server 的 ONTAP 工具執行個體都會顯示摘要頁面。您可以管理與特定 ONTAP 工具執行個體和 vCenter Server 相關聯的儲存系統、但如果您執行多個 ONTAP 工具執行個體、則應將每個儲存系統的登錄資訊分開。
