---
permalink: configure/concept_configure_storage_capability_profiles.html 
sidebar: sidebar 
keywords: storage capability profiles 
summary: Vasa Provider for ONTAP 支援功能、可讓您建立儲存功能設定檔、並將其對應至儲存設備。這有助於維持整個儲存設備的一致性。您也可以使用VASA Provider來檢查儲存設備與儲存功能設定檔之間的法規遵循情況。 
---
= 儲存功能設定檔總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vasa Provider for ONTAP 支援功能、可讓您建立儲存功能設定檔、並將其對應至儲存設備。這有助於維持整個儲存設備的一致性。您也可以使用VASA Provider來檢查儲存設備與儲存功能設定檔之間的法規遵循情況。

儲存功能是一組儲存系統屬性、可識別特定層級的儲存效能、儲存效率及其他功能、例如與儲存功能相關的儲存物件加密。

對於傳統的資料存放區、您可以使用儲存功能設定檔、以一致的方式建立具有通用屬性的資料存放區、並將QoS原則指派給這些資料存放區。在資源配置期間、VSC會顯示符合儲存功能設定檔的叢集、SVM和集合體。您可以使用「儲存對應」功能表中的*全域自動產生設定檔*選項、從現有的傳統資料存放區產生儲存功能設定檔。建立設定檔之後、您可以使用VSC來監控資料存放區與設定檔的相容性。

搭配vVols資料存放區使用時、資源配置精靈可以使用多個儲存功能設定檔、在FlexVol 資料存放區中建立不同的支援區。您可以使用VM儲存原則、自動建立虛擬機器的vVols、使其符合FlexVol 所定義的適當功能。例如、您可以為一般儲存類別建立設定檔（例如效能限制和其他功能、例如加密或FabricPool VMware等）。您可以稍後在vCenter Server中建立VM儲存原則、以代表虛擬機器的商業類別、並依名稱將這些原則連結至適當的儲存功能設定檔（例如：正式作業、測試、人力資源）。

搭配vVols使用時、儲存功能設定檔也可用來設定個別虛擬機器的儲存效能、並將其放在FlexVol vVols資料存放區的VMware Volume上、以最符合效能需求。您可以針對效能指定最低和/或最高IOPS的QoS原則。您可以在最初配置虛擬機器時使用預設原則、或是在業務需求變更時稍後變更VM儲存原則。本版ONTAP 的更新版本的預設儲存功能設定檔：

* AFF_Thick
* FAS _ MAX20
* FAS預設值
* AFF_Default
* AFF_Tiering
* AFF_Encrypted
* AFF_Encrypted_Tiering
* AFF_Encrypted_Min50
* 白金級
* 銅級


然後vCenter Server會將LUN或磁碟區的儲存功能與該LUN或磁碟區上的資源存放區建立關聯。這可讓您在符合虛擬機器儲存設定檔的資料存放區中配置虛擬機器、並確保資料存放區叢集中的所有資料存放區都具有相同的儲存服務層級。

利用VMware Tools、您可以使用新的儲存功能設定檔來設定每個虛擬磁碟區（vVols）資料存放區、以支援在同一個vVols資料存放區上配置具有不同IOPS需求的虛擬機器。ONTAP在執行具有IOPS需求的VM資源配置工作流程時、所有vVols資料存放區都會列在相容的資料存放區清單中。


NOTE: 當您嘗試為6.5之前的vCenter Server配置或修改虛擬機器時、相容的資料存放區清單中只會列出VVols資料存放區、其中包含效能設定為「MAX IOPS」的儲存功能設定檔。其餘vVols資料存放區會列在不相容的資料存放區清單中。您可以忽略此分類、並從不相容的資料存放區清單中選取任何vVols資料存放區、以進行資源配置或修改虛擬機器。



== 建立及編輯儲存功能設定檔的考量事項

您應該瞭解建立和編輯儲存功能設定檔的考量事項。

* 您只能在AFF 靜態系統上設定最低IOPS。
* 您可以在虛擬磁碟區（vVols）資料存放區層級設定QoS度量。
+
此功能可為虛擬資料存放區上配置的同一部虛擬機器的不同VMDK指派不同的QoS度量、提供更大的靈活度。

* 您可以設定FAS 適用於既用於既用於既用於又用於AFF等 資料存放區的儲存功能設定檔。
+
對於靜態和靜態系統、您可以將空間保留區設定為厚或薄。FAS AFF

* 您可以使用儲存功能設定檔為資料存放區提供加密功能。
* 從ONTAP VMware vSphere的舊版版版VMware vSphere升級至ONTAP 最新版的VMware vCenter工具後、您無法修改現有的儲存功能設定檔（建立於7.2版之前）。
+
保留舊版儲存功能設定檔、以提供向下相容性。如果未使用預設範本、則在升級至ONTAP 最新版的VMware Tools期間、會覆寫現有的範本、以反映與儲存功能設定檔效能相關的新QoS指標和分層原則。

* 您無法修改或使用舊版儲存功能設定檔來配置新的虛擬資料存放區或VM儲存原則。
* 您必須為所有新的資料存放區使用新的儲存功能設定檔。

