---
permalink: configure/concept_configure_storage_systems_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 您應該使用 ONTAP 工具介面、將儲存系統新增至 ONTAP 工具、並視需要設定預設認證。 
---
= 關於儲存系統ONTAP 的概述、以瞭解有關各種工具的資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該使用 ONTAP 工具介面、將儲存系統新增至 ONTAP 工具、並視需要設定預設認證。

VMware vSphere的VMware vSphere工具提供單一機制、可探索儲存系統並設定儲存認證。ONTAP這些認證提供 ONTAP 權限、讓 ONTAP 工具使用者能夠使用儲存系統執行工作。

在 ONTAP 工具能夠顯示及管理儲存資源之前、 ONTAP 工具必須先探索儲存系統。在探索過程中、您必須提供ONTAP 儲存系統的不必要資訊。這些是與指派給每個儲存系統的使用者名稱和密碼配對相關聯的權限（或角色）。這些使用者名稱和密碼配對使用ONTAP 以角色為基礎的存取控制（RBAC）、而且必須從ONTAP 下列項目中設定：您無法在 ONTAP 工具中變更這些認證。您ONTAP 可以使用ONTAP 《系統管理程式》來定義無法執行的角色。


NOTE: 如果您以系統管理員的身分登入、您就會自動擁有該儲存系統的所有權限。

將儲存系統新增至 ONTAP 工具時、您必須提供儲存系統的 IP 位址、以及與該系統相關聯的使用者名稱和密碼配對。您可以設定 ONTAP 工具在儲存系統探索程序期間使用的預設認證、或是在探索到儲存系統時手動輸入認證。新增至 ONTAP 工具的儲存系統詳細資料會自動推送至您在部署中啟用的擴充功能。您不需要手動將儲存設備新增至VASA Provider和儲存複寫介面卡（SRA）。工具和 ONTAP 都支援在叢集層級和儲存虛擬機器（ SVM ）層級新增認證。VASA Provider僅支援新增儲存系統的叢集層級認證。當您新增儲存系統時、 ONTAP 工具外掛程式與儲存系統之間的任何通訊都應該相互驗證。

如果您的環境包含多個 vCenter Server 執行個體、當您從「儲存系統」頁面將儲存系統新增至 ONTAP 工具時、「新增儲存系統」對話方塊會顯示 vCenter Server 方塊、您可以在其中指定要新增儲存系統的 vCenter Server 執行個體。如果您以滑鼠右鍵按一下資料中心名稱來新增儲存系統、您將無法選擇指定vCenter Server執行個體、因為該伺服器已與該資料中心建立關聯。

探索是以下列其中一種方式進行。在每種情況下、您都必須為任何新發現的儲存系統提供認證資料。

* ONTAP 工具服務啟動時、 ONTAP 工具會開始自動背景探索程序。
* 您可以按一下「*儲存系統*」頁面或主機或資料中心上的「全部重新探索」按鈕、從*「動作*」功能表（*「動作*」>*「NetApp ONTAP 資訊工具*」>*「更新主機與儲存資料*」）中選取。您也可以按一下「總覽」區段*入門*索引標籤上的*探索*。


所有 ONTAP 工具功能都需要特定權限才能執行工作。您可以根據與ONTAP 該職務相關的認證資料來限制使用者可以執行的工作。擁有相同儲存系統使用者名稱和密碼配對的所有使用者、都會共用一組儲存系統認證資料、並可執行相同的作業。
