---
permalink: configure/reference_rebalance_vvols_datastore.html 
sidebar: sidebar 
keywords: vVols datastore,rebalancing 
summary: 支援指令來重新平衡資料中心內的各種資料。ONTAP FlexVol主要目標是讓FlexVol 各個不景區之間的空間使用率達到同樣的效果。根據空間使用量、精簡配置、LUN數量和儲存功能設定檔、使用VMware Tools可在現有磁碟區之間重新分配vVols。ONTAP 
---
= 重新平衡vVols資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援指令來重新平衡資料中心內的各種資料。ONTAP FlexVol主要目標是讓FlexVol 各個不景區之間的空間使用率達到同樣的效果。根據空間使用量、精簡配置、LUN數量和儲存功能設定檔、使用VMware Tools可在現有磁碟區之間重新分配vVols。ONTAP

vVols資料存放區的重新平衡是由LUN移動或檔案移動所執行。vVols重新平衡期間考量的條件如下：

* 不支援NFS vVol資料存放區
* 現有FlexVol 的版本不需調整大小、FlexVol 也不會新增新的版本
* 只有FlexVol 具有相同儲存功能或Volume屬性的部分Volume才會重新平衡
* 空間使用率最高的VMware磁碟區可用於重新平衡FlexVol
* 所有與虛擬機器相關的vVols都會移至相同FlexVol 的Vol
* 保留LUN和檔案數限制
* 如果無法在FlexVol 使用率為10%的情況下、重新平衡將不會執行


ReBalance命令會移除空FlexVol 的等量資料區、為其他資料存放區提供空間。因此、此命令可讓您移除不想要FlexVol 的功能區、以便從資料存放區中移除這些功能區。此命令旨在將與虛擬機器相關的所有vVols移至相同FlexVol 的Sflexvolume。在重新平衡開始之前、命令會先執行預先檢查、以將故障降至最低。但即使預先檢查成功、一或多個vVols的重新平衡作業也可能失敗。發生這種情況時、就不會復原重新平衡作業。因此、與虛擬機器相關聯的vVols可能會放置在不同FlexVol 的版本上、並會產生警告記錄。

[NOTE]
====
* 不支援平行資料存放區和虛擬機器作業。
* 您必須在每個vVols重新平衡作業完成後、執行叢集重新探索作業。
* 在vVols重新平衡作業期間、如果識別出大量vVols資料存放區、則傳輸作業會在設定的預設值之後逾時。
+
** 如果發生這種情況、您應該修改「vvol.properties`檔案」、將值設為「offtap.operation.timeout.period.seconds=29700`」、然後重新啟動VASA Provider服務。


* 如果FlexVol 某個不穩定磁碟區有Snapshot快照、則vVols在重新平衡作業期間、由於空間使用率的詳細資料不足、vVols無法正確重新平衡。
* 當容器重新平衡作業期間發生逾時時、您可以將 VASA Provider 屬性 _enable 、 update.vVOL 、 through 、 dindiscovery （ VASA 提供者）設為 true 、以便在 VMware vSphere 和 ONTAP 的 ONTAP 工具之間取得一致的資料。
* 沒有公開的 REST API 可重新平衡 vVol 資料存放區。


====
.*開始之前*
* 從維護主控台產生 Web-CLI 權杖：
+
.. 登入維護主控台。
.. 選擇選項 *1* 設備組態。
.. 選取選項 *12* 產生 Web-CLI 驗證權杖。


* 從 vCenter 或 Web-CLI 取得容器名稱和 FlexVol Volume 名稱。
若要取得附加至容器的 FlexVol Volume 清單、請從 Web-CLI 執行命令 _container list_ 。您可以在 Web-CLI 頁面上找到 Container rebalance 命令的詳細資料。



NOTE: 您必須提供容器名稱、才能在附加至該容器的所有 FlexVol 磁碟區之間執行重新平衡。不過、如果提供 FlexVol Volume 參數、則只會在提供的 FlexVol Volume 中執行重新平衡。

.*步驟*
. 使用 URL 從 Web-CLI 登入 `\https://<OTV-IP>:9083/`
. 執行命令： _container rebalance -container 名稱 = <container-name>

