---
permalink: configure/task_create_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 ONTAP 工具手動建立儲存功能設定檔、根據資料存放區的功能自動產生設定檔、或修改設定檔以符合您的需求。 
---
= 建立儲存功能設定檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP 工具手動建立儲存功能設定檔、根據資料存放區的功能自動產生設定檔、或修改設定檔以符合您的需求。

*您需要的是什麼*

您必須已使用ONTAP VMware vSphere的VMware vCenter功能來登錄VASA Provider執行個體。

設定設定檔之後、您可以視需要編輯設定檔。

*步驟*

. 在 ONTAP 工具首頁上、按一下 * 原則與設定檔 * 。
. 視需要建立設定檔或編輯現有的設定檔：
+
|===


| *如果您想要...* | *執行此操作...* 


 a| 
建立設定檔
 a| 
按一下 * 建立 * 。



 a| 
編輯現有的設定檔
 a| 
從「*儲存功能設定檔*」頁面所列的設定檔中、按一下您要修改的設定檔。

|===
+

NOTE: 若要檢視與現有設定檔相關的值、您可以按一下「儲存功能設定檔」頁面中的設定檔名稱。接著VASA供應商會顯示該設定檔的「摘要」頁面。

. 從 * 新資料存放區 * > * 儲存系統 * 、按一下 * 建立儲存功能設定檔 * 。
+
您會收到下列訊息、以確認離開資料存放區視窗。

+
_ 如此將會關閉目前的工作流程來移除輸入的資料、並開啟「建立儲存功能設定檔」工作流程。是否要繼續？ _

. 按一下 * 是 * 以開啟「建立儲存容量設定檔」視窗。
. 完成「建立儲存能力設定檔」精靈中的頁面、以設定設定檔或編輯值來修改現有設定檔。
+
此精靈中的大部分欄位都是不言自明的。下表說明您可能需要指引的部分欄位。

+
|===


| *欄位* | *解釋* 


 a| 
識別多個設定檔
 a| 
您可以使用名稱和說明索引標籤上的 * 說明 * 欄位來說明儲存功能設定檔（ SCP ）的用途。提供良好的說明非常實用、因為根據所使用的應用程式設定不同的設定檔是很好的做法。

例如、業務關鍵應用程式需要具備支援更高效能的設定檔、例如 AFF 和 ASA 平台。用於測試或訓練的資料存放區可能會使用效能較低的 Flash Array Hybrid 平台設定檔、並啟用所有儲存效率功能和分層功能來控制成本。
平台類型與非對稱旗標的組合決定了 CDP 的類型。例如： Platinal_Asa_Platinum 、 Platinal_AFF_A 、 Platinal_AFF_C

如果您已為vCenter Server啟用「連結」模式、則必須選取要為其建立儲存功能設定檔的vCenter Server。



 a| 
平台
 a| 
從適用於 VMware vSphere 9.13 的 ONTAP 工具開始、您可以使用下列項目的組合來建立儲存功能設定檔：

.. 平台類型：效能、容量和 Flash Array Hybrid
.. 非對稱旗標 - 表示儲存系統的 SAN 最佳化（ All SAN Array ）狀態。
+
*** 當平台類型為 * 效能 * 且非對稱旗標為 * 真 * 時、它會考慮 AFF-A 類型的儲存系統
*** 當平台類型為 * 效能 * 、非對稱旗標為 * 錯誤 * 時、它會考慮採用 ASAA 類型的儲存系統
*** 當平台類型為 * 容量 * 且非對稱旗標為 * 真 * 時、它會考慮 AFF-C 類型的儲存系統
*** 當平台類型為 * Flash 混合式陣列 * 、非對稱旗標為 NA 時、它會考慮 FAS 類型的儲存系統




後續畫面上的選項會根據您選擇的儲存系統類型而更新。



 a| 
傳輸協定
 a| 
您可以根據為儲存系統所選的平台、從列出的可用傳輸協定中進行選擇。在設定虛擬機器時、您可以使用儲存功能設定檔來設定VM儲存原則、而傳輸協定欄位則會根據特定的傳輸協定來篩選資料存放區。「any」欄位可讓您使用所有的傳輸協定。



 a| 
效能
 a| 
您可以使用「效能」索引標籤、為儲存系統設定傳統的QoS原則。

** 當您選取*無*時、不會限制（無限）的QoS原則會套用至資料VVOL。
** 當您選取* QoS原則群組*時、傳統的QoS原則會套用至VVOL。
+
您可以設定*最大IOPS *和*最小IOPS *的值、以便使用QoS功能。如果您選取「無限IOPS」、則「最大IOPS」欄位會停用。套用至傳統資料存放區時、系統會建立QoS原則、並將其「最大IOPS」值指派FlexVol 給一個流通量。搭配vVols資料存放區使用時、系統會針對每個資料vVols資料存放區建立最高IOPS和最低IOPS值的QoS原則。

+
*附註*：

+
*** 最大IOPS和最小IOPS也可套用至FlexVol 傳統資料存放區的流通量。
*** 您必須確保效能指標也不會在儲存虛擬機器（SVM）層級、集合層級或FlexVol VMware Volume層級分別設定。






 a| 
儲存屬性
 a| 
您可在此索引標籤中啟用的儲存屬性、取決於您在「特性設定」索引標籤中選取的儲存類型。

** 如果您選取 Flash Array Hybrid 儲存設備、您可以設定空間保留（粗或細）、啟用重複資料刪除、壓縮及加密。
+
分層屬性已停用、因為此屬性不適用於 Flash Array Hybrid 儲存設備。

** 如果您選擇AFF 了「物件儲存」、就可以啟用加密和分層。
+
根據預設AFF 、重複資料刪除與壓縮功能可用於不支援的功能、而且無法停用。

** 如果您選取 ASA 儲存設備、則可以啟用加密和分層。
+
重複資料刪除和壓縮功能預設為 ASA 儲存設備啟用、無法停用。

+
分層屬性可讓您使用已啟用FabricPool的集合體中的Volume（VASA Provider支援AFF 搭配ONTAP 使用支援的版本、適用於採用Fetic9.4及更新版本的系統）。您可以針對分層屬性設定下列其中一個原則：

** 無：防止將Volume資料移至容量層
** Snapshot：將未與作用中檔案系統相關聯的Volume Snapshot複本使用者資料區塊移至容量層


|===
. 在「摘要」頁面上檢閱您的選擇、然後按一下「*確定*」。
+
建立設定檔之後、您可以返回「儲存對應」頁面、檢視哪些設定檔符合哪些資料存放區。


