---
permalink: configure/task_provision_datastores.html 
sidebar: sidebar 
keywords:  
summary: 資源配置資料存放區會為虛擬機器及其虛擬機器磁碟（VMDK）建立邏輯容器。您可以配置資料存放區、然後將資料存放區附加至單一主機、叢集中的所有主機、或資料中心內的所有主機。 
---
= 配置傳統資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資源配置資料存放區會為虛擬機器及其虛擬機器磁碟（VMDK）建立邏輯容器。您可以配置資料存放區、然後將資料存放區附加至單一主機、叢集中的所有主機、或資料中心內的所有主機。

*您需要的是什麼*

* 若要在直接連線至虛擬儲存主控台（VSC）的SVM上配置資料存放區、您必須使用具有適當權限的使用者帳戶、而非預設vsadmin使用者帳戶或vsadmin角色、將SVM新增至VSC。
+
您也可以新增叢集來配置資料存放區。

* 您必須確保ESXi主機所連線之所有網路的子網路詳細資料都輸入kaminoprefs.xml。
+
請參閱「啟用跨不同子網路的資料存放區裝載」。

* 如果您使用NFS或iSCSI、且ESXi主機與儲存系統之間的子網路不同、則kaminoprefs喜好設定檔中的NFS或iSCSI設定必須包含ESXi主機子網路遮罩。
+
此偏好設定檔也適用於vVols資料存放區建立。如需詳細資訊、請參閱_啟用跨不同子網路的資料存放區裝載_和_設定VSC偏好設定檔_。

* 如果您已啟用VASA Provider並想要指定NFS資料存放區或VMFS資料存放區的儲存功能設定檔、則必須建立一個或多個儲存功能設定檔。
* 若要建立NFSv4.1資料存放區、您必須在SVM層級啟用NFSv4.1。


「*資源配置資料庫*」選項可讓您指定資料存放區的儲存功能設定檔。儲存功能設定檔有助於指定一致的服務層級目標（SLO）、並簡化資源配置程序。只有啟用VASA Provider、才能指定儲存功能設定檔。VMware vSphere的支援下列通訊協定的支援功能：ONTAP

* NFSv3和NFSv4.1
* VMFS5和VMFS6


VSC可以在NFS磁碟區或LUN上建立資料存放區：

* 對於NFS資料存放區、VSC會在儲存系統上建立NFS磁碟區、然後更新匯出原則。
* 對於VMFS資料存放區、VSC會建立新的磁碟區（如果您選取該選項、則會使用現有的磁碟區）、然後建立LUN和igroup。


[NOTE]
====
* 搭配執行VMware 9.8及更新版本的經核准的VMware、支援配置VMFS5和VMFS6資料存放區、最多可配置VMFS LUN和64TB的Volume大小。ONTAP ASA AFF ONTAP
+
在其他平台上、支援的最大LUN大小為16TB。

* VMware不支援使用資料存放區叢集的NFSv4.1。


====
如果資源配置期間未指定儲存功能設定檔、您可以稍後使用「儲存對應」頁面、將資料存放區對應至儲存功能設定檔。您可以將儲存QoS設定、處理量上限（最大IOPS）和處理量層（最小IOPS）套用至資源FlexGroup 庫上的虛擬機器資料VMDK檔案。QoS設定可在資料存放區層級或個別虛擬機器層級套用、只要在資料存放區上按一下滑鼠右鍵即可。只有FlexGroup 以VMware資料存放區做為後盾的資料存放區或虛擬機器、才能使用滑鼠右鍵選項。將QoS套用至資料存放區之後、任何預先存在的資料存放區或虛擬機器QoS設定都會被覆寫。QoS設定無法在資料存放區層級或虛擬機器層級套用至直接SVM上的資料存放區、因為ONTAP 無法在SVM管理層級支援QoS。

*步驟*

. 您可以使用下列其中一項來存取資料存放區資源配置精靈：
+
|===


| *如果您選擇...* | *執行下列...* 


 a| 
vSphere Client首頁
 a| 
.. 按一下*主機與叢集*。
.. 在導覽窗格中、選取您要在其中配置資料存放區的資料中心。
.. 若要指定要掛載資料存放區的主機、請參閱下一步。




 a| 
VMware工具首頁ONTAP
 a| 
.. 按一下「*總覽*」。
.. 按一下*入門*索引標籤。
.. 按一下「*資源配置*」按鈕。
.. 按一下「*瀏覽*」、選取下一步要佈建資料存放區的目的地。


|===
. 指定要掛載資料存放區的主機。
+
|===


| *使資料存放區可供...*使用 | *執行此操作...* 


 a| 
資料中心內的所有主機
 a| 
在資料中心上按一下滑鼠右鍵、然後選取* NetApp ONTAP 功能介紹*>*資源配置資料庫*。



 a| 
叢集中的所有主機
 a| 
在主機叢集上按一下滑鼠右鍵、然後選取* NetApp ONTAP 支援工具*>*資源配置資料庫*。



 a| 
單一主機
 a| 
在主機上按一下滑鼠右鍵、然後選取* NetApp ONTAP 支援工具*>*資源配置資料庫*。

|===
. 完成「New Datastore（新資料存放區）」對話方塊中的欄位、以建立資料存放區。
+
對話方塊中的大部分欄位都是不言自明的。下表說明您可能需要指引的部分欄位。

+
|===


| *章節* | *說明* 


 a| 
一般
 a| 
「新資料存放區資源配置」對話方塊的「一般」區段提供選項、可輸入新資料存放區的目的地、名稱、大小、類型和傳輸協定。您可以選取* NFS*或* VMFS*傳輸協定來設定傳統的資料存放區。此版本可讓您設定大小上限為64TB的VMFS資料存放區。您可以選取「跨ONTAP 整個叢集分配資料存放區資料」選項、以便在FlexGroup 儲存系統上配置一個NetApp Volume。選取此選項會自動取消選取「Use Storage Capability Profile for provisioning」（使用儲存功能設定檔進行資源配置）核取方塊。針對供應資料區、僅會列出9.8以上的不實叢集供您選擇。FlexGroup ONTAPvVols資料存放區類型是用來設定vVols資料存放區。如果已啟用VASA Provider、您也可以決定是否使用儲存功能設定檔。*資料存放區叢集*選項僅適用於傳統資料存放區。您應該使用*進階*選項來指定* VMFS5*或* VMFS6*檔案系統。



 a| 
儲存系統
 a| 
如果您已選取「一般」區段中的選項、則可以選取列出的其中一個儲存功能設定檔。如果您要配置FlexGroup 一個不支援的資料存放區、則不支援此資料存放區的儲存功能設定檔。儲存系統和儲存虛擬機器的系統建議值會填入以供輕鬆使用。但您可以視需要修改這些值。



 a| 
儲存屬性
 a| 
根據預設、VSC會填入* Aggregate *和* Volumes *選項的建議值。您可以根據需求自訂值。由於可管理集合體選擇、因此不支援FlexGroup 將Aggregate選取項目用於不支援的資料存放區ONTAP 。「*進階*」功能表下的*空間保留*選項也會填入以提供最佳結果。



 a| 
摘要
 a| 
您可以檢閱您為新資料存放區指定的參數摘要。「摘要」頁面中有一個新的「Volume樣式」欄位、可讓您區分所建立的資料存放區類型。「Volume樣式」可以是「FlexVol '漢城」或「FlexGroup 漢城」。

|===



NOTE: 作爲傳統資料存放區一部分的元件無法縮減至低於現有大小、但最多可增加120%。FlexGroup在這些FlexGroup 支援資料區上啟用預設快照。。在「摘要」區段中、按一下「*完成*」。

*相關資訊*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/Datastore_inaccessible_when_volume_status_is_changed_to_offline["當Volume狀態變更為離線時、無法存取資料存放區"]
