---
permalink: configure/task_enable_datastore_mounting_across_different_subnets.html 
sidebar: sidebar 
keywords:  
summary: 如果您使用iSCSI或NFS、且ESXi主機與儲存系統之間的子網路不同、則必須修改ONTAP VMware vSphere喜好設定檔案的VMware工具。如果您未修改偏好設定檔、則資料存放區資源配置會失敗、因為Virtual Storage Console（VSC）無法掛載資料存放區。 
---
= 在不同的子網路上啟用資料存放區裝載
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用iSCSI或NFS、且ESXi主機與儲存系統之間的子網路不同、則必須修改ONTAP VMware vSphere喜好設定檔案的VMware工具。如果您未修改偏好設定檔、則資料存放區資源配置會因為虛擬儲存主控台（VSC）無法掛載資料存放區而失敗。

*關於此工作*

當資料存放區資源配置失敗時、VSC會記錄下列錯誤訊息：

「無法繼續。當控制器上的核心IP位址與位址相互參照時、找不到IP位址。

找不到與這些主機的NFS掛載磁碟區相符的網路

*步驟*

. 登入vCenter Server執行個體。
. 使用統一化應用裝置虛擬機器啟動維護主控台。
+
link:reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html["VMware ONTAP vSphere的維護主控台"]

. 輸入「4」以存取「Support and Diagnostics（支援與診斷）」選項。
. 輸入「2」存取存取「存取診斷Shell」選項。
. 輸入「vi /opt/NetApp/vscserver/etc/kamino/kaminoprefs.xml」以更新「kaminoprefs.xml」檔案。
. 更新「kaminoprefs.xml」檔案。
+
|===


| *如果您使用...* | *執行此操作...* 


 a| 
iSCSI
 a| 
將輸入金鑰「efault.allow.iscsi.mount.networks`從all」的值變更為ESXi主機網路的值。



 a| 
NFS
 a| 
將輸入金鑰「efault.allow.nfs.mount.networks`從all」的值變更為ESXi主機網路的值。

|===
+
喜好設定檔包含這些項目金鑰的範例值。

+

NOTE: 「all」值並不代表所有網路。「all」值可讓主機與儲存系統之間的所有相符網路用於掛載資料存放區。指定主機網路時、您只能在指定的子網路上啟用掛載。

. 儲存並關閉「kaminoprefs.xml」檔案。

