---
permalink: configure/task_register_oncommand_api_services_with_ontap_tools.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 如果您使用ONTAP 的是VMware Virtual Volumes（vVols）9.6或更早版本、則vVols儀表板只有在您註冊OnCommand 了適用於VASA Provider的EAPI Services以取得vVols VM和資料存放區報告的資料時、才能顯示VMware Virtual Volumes（vVols）資料存放區和虛擬機器的詳細資料。 
---
= 使用OnCommand 各種功能來註冊VMware API服務ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用ONTAP 的是VMware Virtual Volumes（vVols）9.6或更早版本、則vVols儀表板只有在您註冊OnCommand 了適用於VASA Provider的《for VASA API Services for VASA Provider》（適用於VASA供應商的英文版API服務）以取得VVols VM和資料存放區報告的資料時、才能顯示VMware Virtual Volumes（vVols）和

*您需要的是什麼*

您必須已從OnCommand NetApp支援網站下載《21：NetApp API Services 2.1或更新版本」。


NOTE: vVols儀表板只有在SAN vVols資料存放區和虛擬機器使用ONTAP VMware 9.3或更新版本進行設定時、才會顯示效能指標。

*步驟*

. 從「VMware Tools」首頁、按一下ONTAP 「*設定*」。
. 按一下「管理設定」索引標籤中的*管理擴充功能*。
. 使用「Register OnCommand API Services」（登錄支援API服務）滑桿來啟用OnCommand 「支援不支援的API服務」。
. 輸入OnCommand 適用於《介紹API服務的IP位址、服務連接埠和認證資料。
+
您也可以使用「管理VASA提供者延伸」對話方塊進行下列修改：

+
** 在OnCommand 認證資料有任何變更時、更新《程式驗證API服務註冊表（英文）：
** 當OnCommand 您不再需要vVols儀表板時、可取消登錄《程式設計API服務（英文）」。
+
您必須清除「Register OnCommand MorvedAPI Services」（登錄不景點API服務）核取方塊、才能移除OnCommand VASA Provider的「不景點API服務」登錄。



. 按一下「 * 套用 * 」。
+
vVols儀表板只會在ONTAP 完成對錶板API服務的登錄OnCommand 之後、才會顯示有關支援功能不全的資料儲存區的指標、以供參考9.6或更早版本的SAN vVols資料儲存區。



*相關資訊*

https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]
