---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: 當您第一次在vSphere Client中執行虛擬儲存主控台（VSC）時、VSC會探索ESXi主機、其LUN和NFS匯出、以及擁有這些LUN和匯出的NetApp儲存系統。 
---
= 探索儲存系統與主機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您第一次在vSphere Client中執行虛擬儲存主控台（VSC）時、VSC會探索ESXi主機、其LUN和NFS匯出、以及擁有這些LUN和匯出的NetApp儲存系統。

*您需要的是什麼*

* 所有ESXi主機都必須開啟電源並連線。
* 所有要探索的儲存虛擬機器（ SVM ）都必須執行、而且每個叢集節點必須至少有一個資料 LIF 已設定為使用中的儲存傳輸協定（ NFS 、 iSCSI 、 FC 或 NVMe / FC ）。


*關於此工作*

您可以隨時探索新的儲存系統或更新現有儲存系統的相關資訊、以取得最新的容量和組態資訊。您也可以修改VSC用來登入儲存系統的認證資料。

在探索儲存系統時、VSC會從由vCenter Server執行個體管理的ESXi主機收集資訊。

*步驟*

. 從vSphere Client首頁選取*主機與叢集*。
. 右鍵單擊所需的數據中心，然後選擇 *NetApp ONTAP tools*>* Update Host and Storage Data* 。
+
VSC 會顯示「確認」對話方塊、通知您此動作將重新啟動所有已連線儲存系統的探索、並可能需要幾分鐘的時間。您要繼續嗎？

. 按一下 * 是 * 。
. 選取狀態為的探索到儲存控制器 `Authentication Failure`，然後單擊 * 操作 * > * 修改 * 。
. 在「*修改儲存系統*」對話方塊中填寫必要資訊。
. 對所有儲存控制器重複步驟 4 和 5 `Authentication Failure` 狀態。


探索程序完成後、請執行下列步驟：

* 使用VSC來設定主機的ESXi主機設定、這些主機會在「介面卡設定」欄、「MPIO設定」欄或「NFS設定」欄中顯示警示圖示。
* 提供儲存系統認證資料。

