---
permalink: configure/task_provision_datastores.html 
sidebar: sidebar 
keywords:  
summary: 資源配置資料存放區會為虛擬機器及其虛擬機器磁碟（VMDK）建立邏輯容器。您可以配置資料存放區、然後將資料存放區附加至單一主機、叢集中的所有主機、或資料中心內的所有主機。 
---
= 配置傳統資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資源配置資料存放區會為虛擬機器及其虛擬機器磁碟（VMDK）建立邏輯容器。您可以配置資料存放區、然後將資料存放區附加至單一主機、叢集中的所有主機、或資料中心內的所有主機。

*您需要的是什麼*

* 若要在直接連線至 ONTAP 工具的 SVM 上佈建資料存放區、您必須使用具有適當權限的使用者帳戶、而非預設的 vsadmin 使用者帳戶或 vsadmin 角色、將 SVM 新增至 ONTAP 工具。
+
您也可以新增叢集來配置資料存放區。

* 您必須確保ESXi主機所連線之所有網路的子網路詳細資料都輸入kaminoprefs.xml。
+
請參閱「啟用跨不同子網路的資料存放區裝載」。

* 如果您使用NFS或iSCSI、且ESXi主機與儲存系統之間的子網路不同、則kaminoprefs喜好設定檔中的NFS或iSCSI設定必須包含ESXi主機子網路遮罩。
+
此偏好設定檔也適用於vVols資料存放區建立。如需詳細資訊、請參閱 _ 啟用跨不同子網路的資料存放區裝載 _ 和 _ 設定 ONTAP 工具喜好設定檔案 _ 。

* 如果您已啟用VASA Provider並想要指定NFS資料存放區或VMFS資料存放區的儲存功能設定檔、則必須建立一個或多個儲存功能設定檔。
* 若要建立NFSv4.1資料存放區、您必須在SVM層級啟用NFSv4.1。


「*資源配置資料庫*」選項可讓您指定資料存放區的儲存功能設定檔。儲存功能設定檔有助於指定一致的服務層級目標（SLO）、並簡化資源配置程序。只有啟用VASA Provider、才能指定儲存功能設定檔。VMware vSphere的支援下列通訊協定的支援功能：ONTAP

* NFSv3和NFSv4.1
* VMFS5和VMFS6
* 從 vSphere 8.0 版本開始、 VVol 資料存放區支援 NVMe / FC 傳輸協定。


ONTAP 工具可以在 NFS 磁碟區或 LUN 上建立資料存放區：

* 對於 NFS 資料存放區、 ONTAP 工具會在儲存系統上建立 NFS 磁碟區、然後更新匯出原則。
* 對於 VMFS 資料存放區、 ONTAP 工具會建立新的磁碟區（如果您選取該選項、則會使用現有的磁碟區）、然後建立 LUN 和 igroup 。


[NOTE]
====
* ONTAP 工具可在所有執行 ONTAP 9.8 或更新版本的 ASA 系統、以及執行 ONTAP 9.12.1P2 或更新版本的所有其他系統上、支援最多配置 VMFS LUN 和磁碟區大小 64TB 的 VMFS6 資料存放區。
+
在其他平台上、支援的最大LUN大小為16TB。

* VMware不支援使用資料存放區叢集的NFSv4.1。


====
* 對於Kerberos驗證、您需要下列項目：
+
** Windows機器搭配Active Directory（AD）
** 網域名稱伺服器（DNS）
** 金鑰發佈中心（Kdc）
** 配置Kerberos的儲存系統（叢集）ONTAP
** 已設定Kerberos的ESXi主機




如果資源配置期間未指定儲存功能設定檔、您可以稍後使用「儲存對應」頁面、將資料存放區對應至儲存功能設定檔。您可以將儲存QoS設定、處理量上限（最大IOPS）和處理量層（最小IOPS）套用至資源FlexGroup 庫上的虛擬機器資料VMDK檔案。QoS設定可在資料存放區層級或個別虛擬機器層級套用、只要在資料存放區上按一下滑鼠右鍵即可。只有FlexGroup 以VMware資料存放區做為後盾的資料存放區或虛擬機器、才能使用滑鼠右鍵選項。將QoS套用至資料存放區之後、任何預先存在的資料存放區或虛擬機器QoS設定都會被覆寫。無法在資料存放區層級或虛擬機器層級上套用 QoS 設定、以供 SVM 使用者配置的資料存放區使用、因為 ONTAP 在 SVM 管理層級不支援 QoS 。

*步驟*

. 您可以使用下列其中一項來存取資料存放區資源配置精靈：
+
|===


| *如果您選擇...* | *執行下列...* 


 a| 
vSphere Client首頁
 a| 
.. 按一下*主機與叢集*。
.. 在導覽窗格中、選取您要在其中配置資料存放區的資料中心。
.. 若要指定要掛載資料存放區的主機、請參閱下一步。




 a| 
VMware工具首頁ONTAP
 a| 
.. 按一下「*總覽*」。
.. 按一下*入門*索引標籤。
.. 按一下「*資源配置*」按鈕。
.. 按一下「*瀏覽*」、選取下一步要佈建資料存放區的目的地。


|===
. 指定要掛載資料存放區的主機。
+
|===


| *使資料存放區可供...*使用 | *執行此操作...* 


 a| 
資料中心內的所有主機
 a| 
在資料中心上按一下滑鼠右鍵、然後選取* NetApp ONTAP 功能介紹*>*資源配置資料庫*。



 a| 
叢集中的所有主機
 a| 
在主機叢集上按一下滑鼠右鍵、然後選取* NetApp ONTAP 支援工具*>*資源配置資料庫*。



 a| 
單一主機
 a| 
在主機上按一下滑鼠右鍵、然後選取* NetApp ONTAP 支援工具*>*資源配置資料庫*。

|===
. 完成「New Datastore（新資料存放區）」對話方塊中的欄位、以建立資料存放區。
+
對話方塊中的大部分欄位都是不言自明的。下表說明您可能需要指引的部分欄位。

+
|===


| *章節* | *說明* 


 a| 
一般
 a| 
「新資料存放區資源配置」對話方塊的「一般」區段提供選項、可輸入新資料存放區的目的地、名稱、大小、類型和傳輸協定。

您可以選擇 *NFS* 、 *VMS* 或 *vVols* 類型來設定資料存放區。當您選取 vVols 類型時、則可以使用 NVMe / FC 傳輸協定。


NOTE: ONTAP 9.91P3 及更新版本支援 NVMe / FC 傳輸協定。

** NFS ：您可以使用 NFS3 或 NFS4.1 傳輸協定來配置 NFS 資料存放區。
+
您可以選取選項 * 跨 ONTAP 叢集散佈資料存放區資料 * 、在儲存系統上佈建 FlexGroup Volume 。選取此選項會自動取消選取核取方塊 * 使用儲存功能設定檔進行資源配置 * 。

** VMFS ：您可以使用 iSCSI 或 FC/FCoE 通訊協定來配置檔案系統類型為 vmf5 或 VMFS6 的 VMFS 資料存放區。
+

NOTE: 如果已啟用 VASA Provider 、則您可以選擇使用儲存功能設定檔。





 a| 
Kerberos驗證
 a| 
如果您在*一般*頁面中選取NFS 4.1、請選取安全性層級。

Kerberos驗證僅支援FlexVols。



 a| 
儲存系統
 a| 
如果您已選取「一般」區段中的選項、則可以選取列出的其中一個儲存功能設定檔。

** 如果您要配置FlexGroup 一個不支援的資料存放區、則不支援此資料存放區的儲存功能設定檔。儲存系統和儲存虛擬機器的系統建議值會填入以供輕鬆使用。但您可以視需要修改這些值。
** 對於Kerberos驗證、會列出啟用Kerberos的儲存系統。




 a| 
儲存屬性
 a| 
根據預設、 ONTAP 工具會填入 * Aggregate * 和 * Volumes * 選項的建議值。您可以根據需求自訂值。由於可管理集合體選擇、因此不支援FlexGroup 將Aggregate選取項目用於不支援的資料存放區ONTAP 。

「*進階*」功能表下的*空間保留*選項也會填入以提供最佳結果。

（可選）您可以在*變更啟動器群組名稱*欄位中指定啟動器群組名稱。

** 如果還不存在新的啟動器群組、則會以此名稱建立新的啟動器群組。
** 傳輸協定名稱會附加至指定的啟動器群組名稱。
** 如果在選定的啟動器中找到現有的igroup、則會以提供的名稱重新命名igroup、並重新使用。
** 如果您未指定igroup名稱、則會以預設名稱建立igroup。




 a| 
摘要
 a| 
您可以檢閱您為新資料存放區指定的參數摘要。

「Volume樣式」欄位可讓您區分所建立的資料存放區類型。「Volume樣式」可以是「FlexVol '漢城」或「FlexGroup 漢城」。

|===
+

NOTE: 作爲傳統資料存放區一部分的元件無法縮減至低於現有大小、但最多可增加120%。FlexGroup在這些FlexGroup 支援資料區上啟用預設快照。

. 在「摘要」區段中、按一下「*完成*」。


*相關資訊*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/Datastore_inaccessible_when_volume_status_is_changed_to_offline["當Volume狀態變更為離線時、無法存取資料存放區"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-kerberos-concept.html["支援Kerberos ONTAP"]

https://docs.netapp.com/us-en/ontap/nfs-admin/requirements-configuring-kerberos-concept.html["使用NFS設定Kerberos的需求"]

https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_kerberos_realm_services.html["使用System Manager管理Kerberos領域服務- ONTAP 支援更新版本"]

https://docs.netapp.com/us-en/ontap/nfs-config/create-kerberos-config-task.html["在資料LIF上啟用Kerberos"]

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-BDCB7500-72EC-4B6B-9574-CFAEAF95AE81.html["設定ESXi主機進行Kerberos驗證"]
