---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: 您可以手動將儲存系統新增至 ONTAP 工具。 
---
= 新增儲存系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以手動將儲存系統新增至 ONTAP 工具。


NOTE: 如果 ONTAP 叢集已啟用 SAML 、則會以基本驗證方式與 ONTAP 進行通訊。

*關於此工作*

每當您啟動 ONTAP 工具或選取 * 重新探索 All （全部） * 選項時、 ONTAP 工具都會自動探索可用的儲存系統。


NOTE: 直接 SVM 不支援 VVOL 資料存放區。

*步驟*

. 使用 ONTAP 工具首頁中的任一選項、將儲存系統新增至 ONTAP 工具：
+
** 按一下「*儲存系統*>*新增*」。或
** 按一下「*總覽*>*入門*」、然後按一下「新增儲存系統」下的「*新增*」按鈕。


. 在「*新增儲存系統*」對話方塊中、輸入該儲存系統的管理IP位址和認證。
+
當您新增儲存系統時、 ONTAP 工具外掛程式與儲存系統之間的任何通訊都應該相互驗證。

+
您也可以使用叢集或SVM的IPv6位址來新增儲存系統。

+
當您從「 ONTAP 工具儲存系統」頁面新增儲存設備時、請指定儲存設備所在的 vCenter Server 執行個體。「新增儲存系統」對話方塊提供可用vCenter Server執行個體的下拉式清單。如果您要將儲存設備新增至已與 vCenter Server 執行個體相關聯的資料中心、 ONTAP 工具就不會顯示此選項。

+
附註：

+
** 從 ONTAP 工具 9.12 版本開始、所有 ONTAP 儲存系統通訊都是透過憑證型驗證進行。
** 當用戶端或叢集憑證無效時、不允許使用傳統的資料存放區動作、例如刪除、調整大小和掛載。
** 當用戶端或叢集憑證無效時、不允許使用 vVol 資料存放區動作、例如 Expand Storage 、 Mount datastore 。
** 由於這些動作不需要 ONTAP 通訊、因此允許執行刪除、移除儲存和編輯內容等動作。
** 若要新增具有 SVM 範圍使用者的儲存系統、儲存系統叢集管理員必須編輯使用者、並將驗證方法 * 憑證 * 新增至應用程式 HTTP 和 ONTAPI 。
+
在進階選項中、有兩種方法可以上傳 * ONTAP 叢集憑證 * ：

+
... * 自動擷取 * - 自動擷取憑證。
... * 手動上傳 * ：您需要手動瀏覽至憑證所在的位置、然後上傳憑證。




. 新增所有必要資訊後、請按一下「*確定*」。
+
隨即出現授權叢集憑證快顯視窗。

. 按一下 * 顯示憑證 * 以檢視憑證詳細資料。按一下 * 是 * 以新增儲存系統

