---
permalink: manage/concept_virtual_storage_console_reports.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用ONTAP 「VMware Tools主控台報告」功能表來檢視特定vCenter Server中所選VSC執行個體所管理之所有資料存放區的預先定義報告。您可以執行排序和匯出報告等作業。 
---
= 功能性工具資料存放區和vVols報告總覽ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 「參考工具」主控台*「報告」*功能表來檢視特定vCenter Server中所選VSC執行個體所管理之所有資料存放區的預先定義報告。您可以執行排序和匯出報告等作業。

報告會顯示有關資料存放區和虛擬機器的詳細資訊、讓您能夠檢閱及識別vCenter Server中資料存放區和虛擬機器的潛在問題

您可以檢視、排序及匯出報告。

虛擬儲存主控台（VSC）提供下列預先定義的報告：

* 資料存放區報告
* 虛擬機器報告
* VVols資料存放區報告
* VVols虛擬機器報告




== 資料存放區報告

資料存放區報告提供有關傳統資料存放區和在這些資料存放區上建立之虛擬機器的詳細資訊。

傳統儀表板可讓您檢閱及識別vCenter Server中資料存放區和虛擬機器的潛在問題。您可以檢視、排序及匯出報告。傳統資料存放區和虛擬機器的資料報告由vCenter Server提供。但FlexGroup 由於推出支援支援支援支援功能的支援功能、ONTAP 因此部分指標如延遲、處理量和IOPS則是從支援的功能中取得。


NOTE: 不支援檔案監控FlexGroup 功能、以利在直接儲存虛擬機器（SVM）上設定的資料存放區。

資料存放區提供下列預先定義的報告：

* 資料存放區報告
* 虛擬機器報告


*資料存放區報告*

資料存放區報告功能表提供下列資料存放區參數的相關資訊：

* 資料存放區名稱
* 資料存放區類型：NFS或VMFS
* Volume樣式
+
Volume樣式可以是FlexVol 一個「聲音量」或FlexGroup 「聲音量」。

* 可用空間
* 已用空間
* 總空間
* 使用空間百分比
* 可用空間百分比
* IOPS
+
報告會顯示資料存放區的IOPS。

* 延遲
+
報告會顯示資料存放區的延遲資訊。

+
您也可以確認產生報告的時間。資料存放區報告功能表可讓您根據需求來組織報告、然後使用*匯出至CSV*按鈕匯出組織報告。報告中的資料存放區名稱是導覽至所選資料存放區之「監控」索引標籤的連結、您可在其中檢視資料存放區效能指標。



*虛擬機器報告*

「虛擬機器報告」功能表提供所有使用VSC針對所選vCenter Server所配置之資料存放區的虛擬機器效能指標。虛擬機器報告中所顯示的虛擬機器度量是每30分鐘收集一次的歷史資料、用於傳統資料存放區上的虛擬機器。表格中會新增「上次重新整理時間」和「下次重新整理時間」、以提供資料收集時間及下次資料收集時間的詳細資料。

* 虛擬機器名稱
* 資料存放區名稱
* Volume樣式
+
Volume樣式可以FlexVol 是一個「聲音量」或FlexGroup 「聲音量」。

* 來源
+
收集虛擬機器詳細資料的來源可以ONTAP 是VMware或vCenter Server。

* 延遲
+
報告會顯示虛擬機器在所有與虛擬機器相關聯的資料存放區之間的延遲時間。

* IOPS
* 處理量
* 承諾容量
+
報告會顯示虛擬機器已提交容量的值。

* 主機
+
報告會顯示可供虛擬機器使用的主機系統。

* 正常運作時間
+
報告會顯示虛擬機器已開機且可在ESXi主機上使用的時間。

* 電源狀態
+
報告會顯示虛擬機器是開啟還是關閉。



報告中的每個虛擬機器名稱都是指向所選虛擬機器之「監控」索引標籤的連結。您可以根據需求排序虛擬機器報告、並將報告匯出為.CSV檔案、然後將報告儲存在本機系統上。報告的時間戳記也會附加至儲存的報告。

對於FlexGroup 以支援的虛擬機器、當新虛擬機器開機時、檔案會登錄ONTAP 以供在VMware上監控。從ONTAP 無法存取虛擬機器報告時、會取得延遲、處理量和IOPS的歷史數據。



== vVols報告

vVols報告會顯示有關VMware虛擬磁碟區（vVols）資料存放區和這些資料存放區上所建立之虛擬機器的詳細資訊。vVols儀表板可讓您檢閱及識別vCenter Server中vVols資料存放區和虛擬機器的潛在問題。

您可以檢視、組織及匯出報告。vVols資料存放區和虛擬機器的資料報告是ONTAP 由VMware提供、並搭配OnCommand 使用VMware API Services。

VVols提供下列預製報告：

* VVols資料存放區報告
* VVols VM報告


* vVols資料存放區報告*

vVols Datastore Report功能表提供下列資料存放區參數的相關資訊：

* vVols資料存放區名稱
* 可用空間
* 已用空間
* 總空間
* 使用空間百分比
* 可用空間百分比
* IOPS
* 延遲效能指標可用於ONTAP 以NFS為基礎的vVols資料存放區、位於更新版本的Sv9.8。您也可以確認產生報告的時間。vVols Datastore Report功能表可讓您根據需求來組織報告、然後使用* Export to CSV*按鈕來匯出組織報告。報告中的每個SAN vVols資料存放區名稱都是導覽至所選SAN vVols資料存放區的「監控」索引標籤的連結、您可以使用該索引標籤來檢視效能指標。


* vVols虛擬機器報告*

vVols虛擬機器摘要報告功能表提供所有使用SAN vVols資料存放區的虛擬機器效能指標、這些虛擬機器是由VASA Provider針對ONTAP 所選vCenter Server進行資源配置的。VM報告中顯示的虛擬機器度量為虛擬機器vVols資料存放區上每10分鐘收集一次的歷史資料。表格中會新增「上次重新整理時間」和「下次重新整理時間」、以提供資料收集時間及下次資料收集時間的相關資訊。

* 虛擬機器名稱
* 承諾容量
* 正常運作時間
* IOPS
* 處理量
+
報告會顯示虛擬機器是開啟還是關閉。

* 邏輯空間
* 主機
* 電源狀態
* 延遲
+
報告會顯示與虛擬機器相關聯之所有vVols資料存放區中的虛擬機器延遲。



報告中的每個虛擬機器名稱都是指向所選虛擬機器之「監控」索引標籤的連結。您可以根據需求來組織虛擬機器報告、以「.CSV」格式匯出報告、然後將報告儲存到本機系統。報告的時間戳記會附加至儲存的報告。
