---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 您可以監控效能、並根據ONTAP 使用VMware工具vVols儀表板所選取的參數、檢視vCenter Server中前五大SAN和NAS VMware虛擬Volume（vVols）資料存放區。 
---
= 使用vVols儀表板分析效能資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以監控效能、並根據ONTAP 使用VMware工具vVols儀表板所選取的參數、檢視vCenter Server中前五大SAN和NAS VMware虛擬Volume（vVols）資料存放區。

*您需要的是什麼*

* 如果您使用的是版本為6、9.6或更早版本、則應該啟用OnCommand 了「支援不支援的API Services 2.1」或更新版本ONTAP 。
+
您不需要向OnCommand VASA Provider登錄《EFlash API服務》、即可取得SAN vVols資料存放區或SAN vVols VM資料存放區報告的詳細資料ONTAP 、以供更新版本使用。

+
https://mysupport.netapp.com/site/global/dashboard[]

* 您應該使用ONTAP 適用於儲存系統的不含更新版本的功能。


由供應的IOPS資料ONTAP 會四捨五入、並顯示在vVols儀表板上。可能是ONTAP 因為由供應的實際IOPS值與vVols儀表板上顯示的IOPS值有所不同。支援以NFS為基礎的VVols資料存放區、可提供效能監控功能。ONTAP


NOTE: 如果OnCommand 您是第一次登錄「VMware API服務」、則只有在15到30分鐘後、才能在vVols儀表板上檢視SAN vVols資料存放區的所有效能指標資料。

* vVols儀表板資料會定期重新整理、時間間隔為10分鐘。
* 如果您已從vCenter Server執行個體新增、修改或刪除儲存系統、則vVols儀表板上的資料可能會有一段時間沒有任何變更。
+
這是因為OnCommand 無法從ONTAP 更新的指標上取得更新的資料、而需要花費一些時間。

* vVols儀表板的「總IOPS」值顯示在「總覽」入口小工具中、並非「讀取IOPS值」和「寫入IOPS值」的累計值。
+
讀取IOPS、寫入IOPS和總IOPS是OnCommand 由NetApp API Services提供的獨立數據。如果OnCommand 整體IOPS值與由效益API服務提供的累積IOPS值（讀取IOPS值+寫入IOPS值）有差異、則vVols儀表板上的IOPS值會出現相同差異。

* 以NFS為基礎的資料vVols配置於ONTAP 更新版本9.8及更新版本、會自動在vVols儀表板中登錄以監控效能。


*步驟*

. 在vSphere Client首頁中、按一下* ONTAP 「*」「*」「工具*」。
. 使用* vCenter server*下拉式功能表選取所需的vCenter Server、以檢視資料存放區。
. 按一下* vVols Dashboard *。
+
資料存放區入口小程序提供下列詳細資料：

+
** vCenter Server執行個體中由VASA Provider管理的vVols資料存放區數目
** 前五大vVols資料存放區是根據資源使用量和效能參數、您可以根據所用空間、IOPS或延遲、以及所需的順序來變更資料存放區清單。


. 使用虛擬機器入口小程序檢視虛擬機器的詳細資料。
+
虛擬機器入口小程序提供下列詳細資料：

+
** 使用vCenter Server中的資料存放區的虛擬機器數量ONTAP
** 前五大虛擬機器、以IOPS、延遲、處理量、承諾容量、正常運作時間、 以及邏輯空間、您可以自訂vVols儀表板中前五大虛擬機器的列示方式。






== VVols儀表板資料需求

您必須驗證vVols儀表板的一些重要需求、以顯示VMware虛擬磁碟區（vVols）資料存放區和虛擬機器的動態詳細資料。

下表概述您應該驗證vVols儀表板是否未顯示已配置SAN vVols資料存放區和虛擬機器的效能指標。

|===


| *考量事項* | *說明* 


 a| 
第一次部署OnCommand 功能
 a| 
* 如果您使用ONTAP 的是9.6或更早版本的叢集、那麼您將使用OnCommand 的是《不含任何功能的應用程式集介面服務2.1或更新版本。
+
如果您使用的是更新版本的版本、則OnCommand 不需要向VASA Provider註冊任何不含更新版本的API服務ONTAP 。

* 從NetApp支援網站下載並安裝完《_ OnCommand 關於API服務的安裝與設定指南_》中提供的安裝說明OnCommand 、您必須遵守這些指示。
* 每個VASA Provider執行個體都必須有專屬OnCommand 的EAPI服務執行個體。
+
不能在多個VASA Provider執行個體或vCenter Server之間共享此API服務。OnCommand

* 執行及存取的是無法存取的部分API服務。OnCommand




 a| 
儲存系統
 a| 
* 您使用ONTAP 的是版本不含更新版本的。
* 您使用的是儲存系統的適當認證資料。
* 您的儲存系統已啟用且可供存取。
* 您選取的虛擬機器必須至少使用一個vVols資料存放區、而且I/O作業會在虛擬機器的磁碟上執行。


|===